chachat_rg          = "RG-SandBox"
chachat_vnet        = "Vnet-CHA_Chat"
chachat_nsg         = "NSG-CHAChat"
location            = "eastus"
chachat_domain_name = "companyhelpadvisorchat"
chachat_rt          = "RT-CHAChat"
chachat_sbnt        = "sbnt-chachat"